/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoReportRouteImport } from './routes/demo-report'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiSyncRouteImport } from './routes/api/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoReportRoute = DemoReportRouteImport.update({
  id: '/demo-report',
  path: '/demo-report',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-report': typeof DemoReportRoute
  '/home': typeof HomeRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/sync': typeof ApiSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-report': typeof DemoReportRoute
  '/home': typeof HomeRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/sync': typeof ApiSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo-report': typeof DemoReportRoute
  '/home': typeof HomeRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/sync': typeof ApiSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo-report' | '/home' | '/api/auth' | '/api/sync'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo-report' | '/home' | '/api/auth' | '/api/sync'
  id: '__root__' | '/' | '/demo-report' | '/home' | '/api/auth' | '/api/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoReportRoute: typeof DemoReportRoute
  HomeRoute: typeof HomeRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiSyncRoute: typeof ApiSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-report': {
      id: '/demo-report'
      path: '/demo-report'
      fullPath: '/demo-report'
      preLoaderRoute: typeof DemoReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoReportRoute: DemoReportRoute,
  HomeRoute: HomeRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiSyncRoute: ApiSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
